version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8022:8022"

  #client:
  #  build:
  #    context: .
  #    dockerfile: client.Dockerfile
  #  depends_on:
  #    - server
